-- DataVista recruiting tables on the same SQL Server.
-- Always query with three-part names: DataVista.dbo.<Table>
-- (Database name may be overridden by DataVistaDatabase in local.settings.json.)

CREATE TABLE DataVista.dbo.CR_HireMaster (
  userid NVARCHAR(MAX) NULL,
  USERFIRSTNAME NVARCHAR(MAX) NULL,
  USERLASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEID NVARCHAR(MAX) NULL,
  CANDIDATEFIRSTNAME NVARCHAR(MAX) NULL,
  CANDIDATELASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEEMAIL NVARCHAR(MAX) NULL,
  JOBID NVARCHAR(MAX) NULL,
  JOBREFERENCENUMBER NVARCHAR(MAX) NULL,
  COMPANYNAME NVARCHAR(MAX) NULL,
  COMPANYID NVARCHAR(MAX) NULL,
  JOBTITLE NVARCHAR(MAX) NULL,
  DIVISION NVARCHAR(MAX) NULL,
  AGREEDPAYRATE NVARCHAR(MAX) NULL,
  AGREEDBILLRATE NVARCHAR(MAX) NULL,
  PRIMARYRECRUITERNAME NVARCHAR(MAX) NULL,
  HIREFLAG NVARCHAR(MAX) NULL,
  PLACEMENTDATE NVARCHAR(MAX) NULL,
  STARTDATE NVARCHAR(MAX) NULL,
  Location NVARCHAR(MAX) NULL,
  Quickbooks_ID NVARCHAR(MAX) NULL
);

CREATE TABLE DataVista.dbo.CR_InterviewMaster (
  userid NVARCHAR(MAX) NULL,
  USERFIRSTNAME NVARCHAR(MAX) NULL,
  USERLASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEID NVARCHAR(MAX) NULL,
  CANDIDATEFIRSTNAME NVARCHAR(MAX) NULL,
  CANDIDATELASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEEMAIL NVARCHAR(MAX) NULL,
  JOBID NVARCHAR(MAX) NULL,
  JOBREFERENCENUMBER NVARCHAR(MAX) NULL,
  JOBTITLE NVARCHAR(MAX) NULL,
  DIVISION NVARCHAR(MAX) NULL,
  INTERVIEWFLAG NVARCHAR(MAX) NULL,
  INTERVIEWDATE NVARCHAR(MAX) NULL,
  AGREEDPAYRATE NVARCHAR(MAX) NULL,
  PRIMARYRECRUITERNAME NVARCHAR(MAX) NULL,
  COMPANYNAME NVARCHAR(MAX) NULL,
  COMPANYID NVARCHAR(MAX) NULL,
  Location NVARCHAR(MAX) NULL
);

CREATE TABLE DataVista.dbo.CR_RejectMaster (
  userid NVARCHAR(MAX) NULL,
  USERFIRSTNAME NVARCHAR(MAX) NULL,
  USERLASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEID NVARCHAR(MAX) NULL,
  CANDIDATEFIRSTNAME NVARCHAR(MAX) NULL,
  CANDIDATELASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEEMAIL NVARCHAR(MAX) NULL,
  JOBID NVARCHAR(MAX) NULL,
  JOBREFERENCENUMBER NVARCHAR(MAX) NULL,
  COMPANYNAME NVARCHAR(MAX) NULL,
  COMPANYID NVARCHAR(MAX) NULL,
  JOBTITLE NVARCHAR(MAX) NULL,
  DIVISION NVARCHAR(MAX) NULL,
  AGREEDPAYRATE NVARCHAR(MAX) NULL,
  PRIMARYRECRUITERNAME NVARCHAR(MAX) NULL,
  REJECTFLAG NVARCHAR(MAX) NULL,
  INTERNALREJECTDATE NVARCHAR(MAX) NULL,
  EXTERNALREJECTDATE NVARCHAR(MAX) NULL,
  REJECTREASON NVARCHAR(MAX) NULL,
  Location NVARCHAR(MAX) NULL
);

CREATE TABLE DataVista.dbo.CR_SubmittalMaster (
  userid NVARCHAR(MAX) NULL,
  USERFIRSTNAME NVARCHAR(MAX) NULL,
  USERLASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEID NVARCHAR(MAX) NULL,
  CANDIDATEFIRSTNAME NVARCHAR(MAX) NULL,
  CANDIDATELASTNAME NVARCHAR(MAX) NULL,
  CANDIDATEEMAIL NVARCHAR(MAX) NULL,
  JOBID NVARCHAR(MAX) NULL,
  JOBREFERENCENUMBER NVARCHAR(MAX) NULL,
  JOBTITLE NVARCHAR(MAX) NULL,
  DIVISION NVARCHAR(MAX) NULL,
  INTERNALSUBMITTALFLAG NVARCHAR(MAX) NULL,
  EXTERNALSUBMITTALFLAG NVARCHAR(MAX) NULL,
  SUBMITTALDATE NVARCHAR(MAX) NULL,
  AGREEDPAYRATE NVARCHAR(MAX) NULL,
  PRIMARYRECRUITERNAME NVARCHAR(MAX) NULL,
  COMPANYNAME NVARCHAR(MAX) NULL,
  COMPANYID NVARCHAR(MAX) NULL,
  Location NVARCHAR(MAX) NULL,
  Quickbooks_ID NVARCHAR(MAX) NULL,
  STARTDATE NVARCHAR(MAX) NULL
);
